// FILE: src/app/layout.tsx

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

// --- Global Components ---
import { ThemeProvider } from '@/components/ThemeProvider';
import { ModeToggle } from '@/components/ModeToggle';
import Header from '@/components/Header'; // A header is usually global, so it goes in the bun!

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'theo.diniz',
  description: 'Generated by create next app',
};

// This is the BUN that wraps everything
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          
          <main>{children}</main>

          <div className="fixed bottom-8 right-50 z-50">
            <ModeToggle />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}